# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-15 21:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artifact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('group', models.CharField(default='', max_length=30)),
                ('version', models.CharField(default='', max_length=200)),
                ('vendor', models.CharField(choices=[(None, 'Select:'), ('pws', 'pws'), ('pws_3rdp', 'pws 3rpd'), ('thirdp', 'thirdp')], default=None, max_length=30)),
                ('var_name', models.CharField(default='', max_length=30)),
                ('built_by', models.CharField(choices=[(None, 'Select:'), ('FullBuild', 'Full Build'), ('opstools', 'opstools'), ('ansible', 'ansible'), ('None', 'None')], default=None, max_length=30)),
                ('date_added', models.DateTimeField(auto_now=True)),
                ('comment', models.CharField(blank=True, default='', max_length=100)),
                ('deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Manifest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('release', models.CharField(default='', max_length=30)),
                ('revision', models.CharField(default='', max_length=30)),
                ('date_added', models.DateTimeField(auto_now=True)),
                ('ext_release', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('sw_type', models.CharField(blank=True, choices=[('PROD', 'Production'), ('OPS', 'Operations')], default='PROD', max_length=30)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='manifest',
            unique_together=set([('release', 'revision')]),
        ),
        migrations.AddField(
            model_name='artifact',
            name='parent_manifest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='release_manifest.Manifest'),
        ),
        migrations.AlterUniqueTogether(
            name='artifact',
            unique_together=set([('parent_manifest', 'name', 'group')]),
        ),
    ]
