# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-18 20:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('branch_name', models.CharField(default='turnk', max_length=32, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name_plural': 'branches',
            },
        ),
    ]
