# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-30 01:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svn_permission', '0002_auto_20180320_2314'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('name', models.CharField(choices=[(b'svnadmin', b'svnadmin'), (b'buildadmin', b'buildadmin'), (b'CMIP_rw', b'CMIP_rw'), (b'CMIP_ro', b'CMIP_ro'), (b'GatewayBE_rw', b'GatewayBE_rw'), (b'GatewayBE_ro', b'GatewayBE_ro'), (b'BL_rw', b'BW_rw'), (b'BL_ro', b'BL_ro')], max_length=64, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=64, unique=True)),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('groups', models.ManyToManyField(to='svn_permission.Group')),
            ],
        ),
        migrations.AlterField(
            model_name='module',
            name='mod_name',
            field=models.CharField(choices=[(b'core2', ((b'JCore', b'JCore'), (b'JCore/BL_Common', b'JCore/BL_Common'), (b'JCore/BL', b'JCore/BL'), (b'JCore/Common', b'JCore/Common'))), (b'ops2', ((b'Ops', b'Ops'), (b'DevOps/Build', b'DevOps/Build'), (b'DevOps/Deploy', b'DevOps/Deploy'))), (b'pws2', ((b'PWS', b'PWS'),)), (b'test2', ((b'Scripts', b'Scripts'), (b'Tools', b'Tools')))], max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='repository',
            name='repo_name',
            field=models.CharField(choices=[(b'core2', b'core2'), (b'ops2', b'ops2'), (b'pws2', b'pws2'), (b'test2', b'test2')], max_length=5, primary_key=True, serialize=False),
        ),
    ]
