# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-01 18:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('svn_permission', '0003_auto_20180329_2147'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartitionTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.CharField(choices=[(b'r', b'ReadOnly'), (b'rw', b'ReadWrite')], default='r', max_length=2)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='svn_permission.Branch')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='svn_permission.Group')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='svn_permission.Module')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='partitiontest',
            unique_together=set([('module', 'branch')]),
        ),
    ]
