# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-02 01:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('svn_permission', '0004_auto_20180401_1440'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupPerm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.CharField(choices=[(b'r', b'ReadOnly'), (b'rw', b'ReadWrite')], default='r', max_length=2)),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='svn_permission.Group')),
            ],
        ),
        migrations.RemoveField(
            model_name='partitiontest',
            name='group',
        ),
        migrations.RemoveField(
            model_name='partitiontest',
            name='permission',
        ),
        migrations.AddField(
            model_name='partitiontest',
            name='group_perm',
            field=models.ManyToManyField(to='svn_permission.GroupPerm'),
        ),
    ]
